# SPDX-FileCopyrightText: 2008-2021 HPDCS Group <rootsim@googlegroups.com>
# SPDX-License-Identifier: CC0-1.0
comment: no

coverage:
  range: 70..90

  status:
    project:
      enabled: yes
      target: auto
      threshold: 3%

    patch: no
    changes: no

