# SPDX-FileCopyrightText: 2008-2021 HPDCS Group <rootsim@googlegroups.com>
# SPDX-License-Identifier: CC0-1.0
coverage:
  range: 70..90

  status:
    project:
      enabled: yes
      target: auto
      threshold: 3%

    patch: false
    changes: false

fixes:
  - "*/::"        # Adjust the relative path of the files (should be relative to git repo's root)
