version = 1
SPDX-PackageName = "ROOT-Sim"
SPDX-PackageSupplier = "HPDCS Group <rootsim@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/ROOT-Sim/core"

[[annotations]]
path = "docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "docs/img/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "AUTHORS"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "ChangeLog"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CODEOWNERS"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ".markdownlint.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".stylelintrc.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".codacy.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2023 HPDCS Group <rootsim@googlegroups.com>"
SPDX-License-Identifier = "CC0-1.0"
