#!/usr/bin/env python3

import os
import re
import sys

_, header_path, source_output = sys.argv

pattern = '([A-Z][0-9A-Za-z]*)([ \t\n\r\f\v]*\()'

with open(header_path, 'r') as f:
    header_str = f.read()

results = set()
for match in re.finditer(pattern, header_str):
    results.add(match.group(1))
    
with open(source_output, 'w') as f:
    f.write('// file generated by a NeuRome build script, all rights reserved\n') # TODO do we need this?
    f.write('const char *neurome_exposed_functions[] = {\n')
    
    if results:
        for function_name in results:
            f.write('\t"{}",\n'.format(function_name))   
    
    f.write('\tnullptr\n};\n')
