/**
 * @file gvt/gvt.c
 *
 * @brief Global Virtual Time
 *
 * For a detailed explanation of the algorithm, see:
 *
 * T. Tocci, A. Pellegrini, F. Quaglia, J. Casanovas-García, and T. Suzumura
 * “ORCHESTRA: An Asynchronous Wait-Free Distributed GVT Algorithm”
 * in Proceedings of the 21st IEEE/ACM International Symposium on Distributed
 * Simulation and Real Time Applications, 2017, pp. 51–58
 *
 * SPDX-FileCopyrightText: 2008-2025 HPCS Group <rootsim@googlegroups.com>
 * SPDX-License-Identifier: GPL-3.0-only
 */
#include <gvt/gvt.h>

#include <arch/timer.h>
#include <core/sync.h>
#include <datatypes/msg_queue.h>
#include <distributed/mpi.h>

#include <assert.h>
#include <math.h>
#include <memory.h>
#include <stdatomic.h>

/// Node phases of the non-blocking GVT algorithm
enum gvt_phase {
	/// Currently not engaged in a GVT algorithm execution
	gvt_phase_idle = 0,
	/// Start the distributed remote messages count reduction
	gvt_phase_sent_reduce,
	/// Wait for the completion of the count reduction MPI collective
	/** Only a single thread per node goes through this phase per reduction */
	gvt_phase_sent_reduce_wait,
	/// Wait for the completion of the count reduction MPI collective
	gvt_phase_sent_wait,
	/// Start the distributed min GVT reduction
	gvt_phase_min_reduce,
	/// Wait for the completion of the min GVT reduction MPI collective
	/** Only a single thread per node goes through this phase per reduction */
	gvt_phase_min_reduce_wait,
	/// Wait for the completion of the min GVT reduction MPI collective
	gvt_phase_min_wait,
};

/// The current phase of the GVT algorithm this thread is in
static _Thread_local enum gvt_phase gvt_phase = gvt_phase_idle;
/// The timer used to plan the execution of the next GVT algorithm
static timer_uint gvt_timer;
/// This keeps the minimum timestamp of messages extracted by the current thread
/** A sort of thread local GVT value used for further reductions */
static _Thread_local simtime_t gvt_accumulator;
/// The target timer before starting the reduction of the count of in-flight messages
static _Thread_local timer_uint flush_phase_until;
/// The amount of time to wait before starting the reduction of the count of in-flight messages
/** Adaptively updated according to success/failures of previous in-flight messages reductions*/
static _Thread_local timer_uint flush_phase_wait_for;
/// A counter used to synchronize threads during the GVT algorithm
static _Atomic rid_t c_a = 0;
/// A counter used to synchronize threads during the GVT algorithm
static _Atomic rid_t c_b = 0;
/// The count of nodes still involved in a GVT computation
/** If this is 0 that means that a new GVT computation can be safely started */
static _Atomic nid_t gvt_nodes;
/// The "color" of the current GVT phase
/** Colors are red if false, yellow if true ;) */
_Thread_local bool gvt_color;
/// The sequence number for remote messages generated by the current thread
_Thread_local uint64_t remote_msg_seq;
/// The count of remote messages received by the current thread
/** We handle separately red and yellow messages */
_Thread_local int64_t remote_msg_balance[2];

/**
 * @brief Initialize the gvt module in the node
 */
void gvt_global_init(void)
{
	gvt_timer = timer_new() + global_config.gvt_period;
}

/**
 * @brief Handle a MSG_CTRL_GVT_START control message
 *
 * Called by the MPI layer in response to a MSG_CTRL_GVT_START control message. Note that, given the structure of the
 * main loop, threads can either call this function while handling remote control messages or while checking the status
 * of the GVT algorithm, which means that all threads will visit the message queue (and accordingly update their local
 * GVT estimation) at least once before proceeding with the reduction of in-flight messages.
 */
void gvt_start_processing(void)
{
	assert(gvt_phase == gvt_phase_idle);
	gvt_accumulator = INFINITY;
	gvt_color = !gvt_color;
	flush_phase_until = timer_hr_new() + flush_phase_wait_for;
	gvt_phase = gvt_phase_sent_reduce;
}

/**
 * @brief Handle a MSG_CTRL_GVT_DONE control message
 *
 * Called by the MPI layer in response to a MSG_CTRL_GVT_DONE control message
 */
void gvt_on_done_ctrl_msg(void)
{
	atomic_fetch_sub_explicit(&gvt_nodes, 1U, memory_order_relaxed);
}

/**
 * @brief Inform the GVT subsystem that a new message is being processed
 * @param msg_t the timestamp of the message being processed
 *
 * Called by the process layer when processing a new message; used in the actual GVT calculation
 */
void gvt_on_msg_extraction(const simtime_t msg_t)
{
	if(unlikely(gvt_accumulator > msg_t))
		gvt_accumulator = msg_t;
}

/**
 * @brief Executes a single step of the node-local GVT phase.
 *
 * This function manages the progression of the node-local GVT algorithm through its phases.
 * Each phase performs specific synchronization and reduction tasks, ensuring that the GVT computation progresses
 * correctly across all threads and nodes.
 *
 * @return -1.0 if the node-local GVT computation has completed, the GVT value otherwise.
 *
 * @details
 * - `gvt_phase_sent_reduce`: Aggregates the count of remote messages sent and transitions to the reduction phase.
 * - `gvt_phase_sent_reduce_wait`: Waits for the completion of the remote message count reduction.
 * - `gvt_phase_sent_wait`: Waits for all remote messages to be processed and transitions to the second reduction phase.
 * - `gvt_phase_min_reduce`: Initiates the reduction of the minimum GVT value across threads.
 * - `gvt_phase_min_reduce_wait`: Waits for the completion of the minimum GVT reduction.
 * - `gvt_phase_min_wait`: Ensures all threads have completed the reduction and transitions to the final phase.
 */
static simtime_t gvt_step(void)
{
	static union {
		_Atomic int64_t atomic;
		int64_t raw;
	} balance = {.raw = 0};

	static union {
		_Atomic simtime_t atomic;
		simtime_t raw;
	} gvt_reduced;

	static int64_t last_balance = 0;

	switch(gvt_phase) {
		case gvt_phase_sent_reduce:
reduce_sent_retry:
			if(atomic_load_explicit(&c_a, memory_order_relaxed) || timer_hr_new() < flush_phase_until)
				break;
			// reduce the node-local remote message balance
			atomic_fetch_add_explicit(&balance.atomic, remote_msg_balance[!gvt_color],
			    memory_order_relaxed);
			remote_msg_balance[!gvt_color] = 0;
			// release balance, which will be acquired by the thread calling the MPI sum reduction
			if(atomic_fetch_add_explicit(&c_b, 1U, memory_order_acq_rel) + 1U != global_config.n_threads) {
				gvt_phase = gvt_phase_sent_wait;
				goto reduce_sent_wait;
			}
			mpi_reduce_sum(&balance.raw);
			atomic_fetch_add_explicit(&c_a, global_config.n_threads, memory_order_relaxed);
			gvt_phase = gvt_phase_sent_reduce_wait;
			/* fallthrough */
		case gvt_phase_sent_reduce_wait:
			if(!mpi_collective_done())
				break;

			last_balance += balance.raw;
			balance.raw = 0;
			gvt_reduced.raw = INFINITY;
			// release last_balance
			atomic_fetch_sub_explicit(&c_b, global_config.n_threads, memory_order_release);
			// no need to set next phase as there's no way to inadvertently rerun this phase code
			/* fallthrough */
		case gvt_phase_sent_wait:
reduce_sent_wait:
			if(atomic_load_explicit(&c_b, memory_order_relaxed))
				break;
			// acquire last_balance
			atomic_load_explicit(&c_b, memory_order_acquire);
			atomic_fetch_sub_explicit(&c_a, 1U, memory_order_relaxed);
			if(last_balance) {
				// we tried to reduce balance too early, increase the flush waiting time
				flush_phase_until += flush_phase_wait_for + 1;
				flush_phase_wait_for += flush_phase_wait_for + 1;
				gvt_phase = gvt_phase_sent_reduce;
				goto reduce_sent_retry;
			}
			// balance confirmed that the flush time was long enough, try to shorten the next one a lil bit
			flush_phase_wait_for = flush_phase_wait_for * 7 / 8;
			gvt_phase = gvt_phase_min_reduce;
			/* Here we need to break to ensure all the threads visit the message queue a second time.
			 * The first visit already happened when each thread call gvt_start_processing(). Given ROOT-Sim
			 * message queue guarantees, two properly timed visits of the message queue per thread (the
			 * first one right after the color switch, the second one right after a successful in-flight
			 * message reduction) are sufficient to guarantee a correct GVT estimation. */
			break;
		case gvt_phase_min_reduce:
			if(atomic_load_explicit(&c_a, memory_order_relaxed))
				break;
			// atomically reduce node-local GVT
			simtime_t expected = INFINITY;
			while(!atomic_compare_exchange_weak_explicit(&gvt_reduced.atomic, &expected, gvt_accumulator,
				  memory_order_relaxed, memory_order_relaxed) &&
			      gvt_accumulator < expected)
				spin_pause();
			// release gvt_reduced, which will be acquired by the thread calling the MPI min reduction
			if(atomic_fetch_add_explicit(&c_b, 1U, memory_order_acq_rel) + 1 != global_config.n_threads) {
				gvt_phase = gvt_phase_min_wait;
				goto reduce_min_wait;
			}
			mpi_reduce_min(&gvt_reduced.raw);
			atomic_fetch_add_explicit(&c_a, global_config.n_threads, memory_order_relaxed);
			gvt_phase = gvt_phase_min_reduce_wait;
			/* fallthrough */
		case gvt_phase_min_reduce_wait:
			if(!mpi_collective_done())
				break;
			// release the memory writing done by mpi_collective_done() when committing the MPI collective
			atomic_fetch_sub_explicit(&c_b, global_config.n_threads, memory_order_release);
			gvt_phase = gvt_phase_min_wait;
			/* fallthrough */
		case gvt_phase_min_wait:
reduce_min_wait:
			if(atomic_load_explicit(&c_b, memory_order_relaxed))
				break;
			// acquire gvt_reduced (potentially written by the commit of the MPI min collective)
			atomic_load_explicit(&c_b, memory_order_acquire);
			return gvt_reduced.raw;
		default:
			__builtin_unreachable();
	}
	return -1.0;
}

/**
 * @brief Signal to the GVT subsystem that this thread is done using the GVT value for its own house keeping
 */
void gvt_handling_done(void)
{
	assert(gvt_phase == gvt_phase_min_wait);
	if(atomic_fetch_sub_explicit(&c_a, 1U, memory_order_relaxed) == 1)
		mpi_control_msg_send_to(MSG_CTRL_GVT_DONE, 0);
	gvt_phase = gvt_phase_idle;
}

/**
 * @brief Execute a step of the GVT algorithm
 * @return the latest GVT value or 0.0 if the algorithm must still complete
 *
 * This function must be called several times by all the processing threads hosted in the nodes involved in the
 * simulation before completing and returning a proper GVT value.
 */
simtime_t gvt_run(void)
{
	if(unlikely(gvt_phase != gvt_phase_idle))
		return gvt_step();

	if(unlikely(!rid && !nid)) {
		const timer_uint t = timer_new();
		if(unlikely(t >= gvt_timer && !atomic_load_explicit(&gvt_nodes, memory_order_relaxed))) {
			gvt_timer = t + global_config.gvt_period;
			atomic_fetch_add_explicit(&gvt_nodes, n_nodes, memory_order_relaxed);
			for(nid_t i = n_nodes - 1; i; --i)
				mpi_control_msg_send_to(MSG_CTRL_GVT_START, i);
			gvt_start_processing();
		}
	} else if(unlikely(atomic_load_explicit(&c_b, memory_order_relaxed))) {
		gvt_start_processing();
	}

	return -1.0;
}

/**
 * @brief Wait for in-flight messages and clear the distributed state of the GVT algorithm
 *
 * This function flushes the remaining remote messages, moreover it makes sure that all the nodes complete the
 * potentially ongoing GVT algorithm so that MPI collectives are inactive.
 */
void gvt_msg_barrier(void)
{
	if(sync_thread_barrier())
		mpi_node_barrier();
	sync_thread_barrier();

	for(int i = 0; i < 2; ++i) { // flush both gvt phases
		gvt_timer = 0;       // this satisfies the timer condition
		while(!gvt_run())
			mpi_remote_msg_handle();
	}
}
