name: Codacy Code Scan

permissions:
  contents: read

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  schedule:
    - cron: '20 2 * * 3'

jobs:
  codacy-security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Codacy Analysis CLI (cppcheck)
        uses: codacy/codacy-analysis-cli-action@v4.4.5
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          tool: cppcheck
          verbose: true
          output: cppcheck.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
      - name: Run Codacy Analysis CLI (bandit)
        uses: codacy/codacy-analysis-cli-action@v4.4.5
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          tool: bandit
          verbose: true
          output: bandit.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
      - name: Upload SARIF results file (cppcheck)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cppcheck.sarif
          category: codacy
      - name: Upload SARIF results file (bandit)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
          category: codacy
