name: REUSE Compliance Check

permissions:
  contents: read

on:
  pull_request:

jobs:
  reuse_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkpout repository
        uses: actions/checkout@v4
      - name: REUSE check
        uses: ROOT-Sim/ci-actions/reuse-check@030cae234d9698712812e888d0d9d13ca8e1814f
