name: REUSE Compliance Check

permissions:
  contents: read

on:
  pull_request:

jobs:
  reuse_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkpout repository
        uses: actions/checkout@v4
      - name: REUSE check
        uses: ROOT-Sim/ci-actions/reuse-check@v1.5.3
