name: update-copyright

on:
  schedule:
    - cron: "0 1 1 1 *"

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update copyright
        uses: ROOT-Sim/ci-actions/update-copyright@030cae234d9698712812e888d0d9d13ca8e1814f
        with:
          branch-to-update: develop
